apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-ef-blankett
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /api/status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /api/status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: false
  ingresses:
    - https://familie-ef-blankett.dev.intern.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
    outbound:
      rules:
        - application: familie-dokument
  env:
    - name: APP_VERSION
      value: '{{version}}'
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi